exclude: '^.venv/'
repos:
  - repo: local
    hooks:
      - id: check_script
        name: check_script
        entry: shell_scripts/pre_commit.sh
        language: script
        types: [python]
        always_run: true